file = open("txt/results1.txt", "w")

print "Python calculations"

file.write("This is some text, generated by a Python script. ")

#file.write("Result_1	3272")
#file.write("Result_2	52")
#file.write("Result_4	3.2384")
#file.write("Result_5	non equal")

file.close()



